# Generated by Django 5.0.4 on 2024-04-19 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0003_submission_report_count_alter_submission_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='was_exported',
            field=models.BooleanField(default=False),
        ),
    ]
