# Generated by Django 5.0.4 on 2024-04-26 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0005_submissioncategory_is_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sorting',
            field=models.CharField(default='by_date', max_length=40),
        ),
    ]
