# Generated by Django 5.0.4 on 2024-06-08 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0006_profile_sorting'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
