# Generated by Django 5.0.4 on 2024-06-08 22:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_main', '0007_submission_done'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfileSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.CharField(max_length=200)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('was_exported', models.BooleanField(default=False)),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_main.platform')),
            ],
        ),
    ]
